### PR TITLE
Security updates

### PR DESCRIPTION
**Pull request by a-frantz**

### CODE REVIEW

**Comment by claymcleod** [comment]
@a-frantz, can you please do two things:

(1) confirm whether or not we should disable appveyor as well? I know it does testing for Windows, but I can't remember if it autobuilds assets or not.
(2) Can you fix these errors?

```##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(41,20): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(45,27): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(56,24): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(57,31): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(63,25): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(68,23): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(74,28): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(249,18): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(258,26): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(263,33): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(269,31): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(274,25): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(280,30): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(303,24): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(359,13): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(361,24): error TS2344: Type 'TArgs' does not satisfy the constraint 'any[]'.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(527,26): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(634,18): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(655,13): error TS2370: A rest parameter must be of an array type.
##[error]D:/a/sjcloud-data-transfer-app/sjcloud-data-transfer-app/node_modules/@types/sinon/index.d.ts(657,25): error TS2344: Type 'TArgs' does not satisfy the constraint 'any[]'.```

**Comment by claymcleod** [comment]
Few other things:

- It appears that logging in using a St. Jude SSO account does not work anymore. Can you confirm?
- The tour appears to be broken.

**Comment by a-frantz** [comment]
There are a number of bugs I was aware of that were present before I started making updates, the SSO issue being one of them. I documented the bugs I found on the Trello board. Was not aware of the tour being broken, but I'll add it to my list of things to fix once the security vulnerabilities are handled.

**Comment by a-frantz** [comment]
I believe this now addresses everything Github was warning us about in the security tab. There are still vulnerabilities according to `npm audit`, however I addressed ~45 that were included in `npm audit` but not Github Security. Seems `npm` is much more stringent.

The remaining ones would require replacing quite a few of our dependencies for alternatives, as there are currently no patches for the packages we are using. I didn't investigate how much work that would entail, but it would require replacing 6 of our core dependencies, some of which do not look easily replaceable.

One exception is a major version change of `webpack`. I saved this vulnerability for last because the version bump introduces many breaking changes that would require significant rewriting, and I don't believe Github Security is concerned with it. `npm` also considers the `webpack@3` vulnerability to be of the lowest concern.

Do we want to ignore `npm audit` and just rely on Github Security?

Here's the current summary for `npm audit`:
```found 10 vulnerabilities (4 low, 4 moderate, 1 high, 1 critical)```

There is currently no way I can find to have Github Security check a branch other than the default one. I'd like to merge this branch without closing the PR so it can update the security advisories to see where we stand, and then reevaluate.

*This branch includes a fix for those typescript semantic errors

**Comment by a-frantz** [comment]
Actually before this gets merged I want to clean up the Gulpfile. I initially just threw it together to get it working, which it does now. But it's incredibly ugly. Going to split it back up into multiple files, which Gulp4 made more complicated than it was in Gulp3, and I didn't want to deal with it at first.

Anyone spotting anything else that needs updating in here?

**Comment by claymcleod** [comment]
Once you get that working, I think we are good on the security updates. You can merge then continue onto the other fixed before cutting the release.

**Pull request merged**
