### PR TITLE
lint code with prettier

### PR DESCRIPTION
**Pull request by a-frantz**

### CODE REVIEW

**Comment by claymcleod** [comment]
@a-frantz Is there a reason why `husky` isn't autoformatting all of this on each commit? Is it just looking at the files that were modified?

**Comment by claymcleod** [comment]
I'm almost inclined to hold off on this until we release the next version, mainly because I fear the merge conflicts that are going to arise.

**Comment by a-frantz** [comment]
I think it might be only doing files that were modified, but I'm not positive. I can look into it. But yes it makes sense to hold off until the next release. The merge conflicts would be a hassle to deal with and none of the current formatting is unreadable or anything.

**Comment by claymcleod** [comment]
Okay, I'll close it for now. Let's be sure to do it after the merge.

**Pull request closed without merging**
