### PR TITLE
Change yarn back to NPM.

### PR DESCRIPTION
**Pull request by claymcleod**
Now that NPM has reached feature parity on package locking with
yarn, I don't see a lot of reason to stay with yarn. That missing
feature was the main reason we switched, but I think using the
default ecosystem is probably better moving forward.

### CODE REVIEW

**Comment by zaeleus** [comment]
I'm fine with going back to npm; it wins in accessibility since it's already installed with node. Given that yarn is almost a drop in replacement, if a developer has it installed, they'll be able to use it as is anyway.

I'm curious what you mean in your commit message though. [npm 5.0.0](https://blog.npmjs.org/post/161081169345/v500) introduced lock files, which was out before the start of this project and the switch (e413301). They also share the same ecosystem/tooling.

**Comment by claymcleod** [comment]
@zaeleus My commit message might not be exactly representative now that you point this out. I thought that we had moved away from `npm` because of issues with the locking and/or some sort of dependency resolving step. I do know that the app was not building correctly using `npm` before. Regardless, it's working correctly now with `npm`, so I'll change the message when we merge.

Can you think of anything else that needs to change here?

**Comment by claymcleod** [comment]
Update: some digging on this showed that one of the packages (`send`) was misconfigured in `package-lock.json`. After refreshing that, it works.

**Comment by a-frantz** [comment]
I think we switched because I was getting build errors on my Windows machine. Can't remember if Clay and Edgar were having them on Mac too. But switching to yarn resolved it either way. If whatever was wrong with npm is fixed now, it makes sense to switch back to the package manager installed with Node.

**Comment by jsunny23** [comment]
Agreed -- if npm works fine for everyone, works and has the features we need, I think its a good idea to use npm.

**Comment by claymcleod** [comment]
Okay great, we'll do this then. I'd merge the changes, but we still have a test failing on Windows. @a-frantz can you take this one?

**Comment by a-frantz** [comment]
It's passing all tests now. Ready to be squashed and merged unless any of you see a problem.

**Pull request merged**
